# pytest.ini
[pytest]
pythonpath = .
testpaths = test pycbc/waveform/tests
addopts = --ignore test/test_fftw_pthreads.py
markers =
    gpu: mark test as requiring GPU hardware / CUDA
    cuda: mark test as requiring NVIDIA CUDA runtime
