# coding: utf-8
# Generated by setup.py for PyCBC on 2026-09-06 07:50:29 +0000.

# general info
version = '0.0a9313'
date = '2026-09-06 07:47:11 +0000'
release = False
last_release = 'None'

# git info
git_hash = '9a6d2adc9aca6349ce004152ed7e49f356214b0f'
git_branch = 'None'
git_tag = 'None'
git_author = 'AI Gareth <AI.Gareth@users.noreply.github.com>'
git_committer = 'xangma <xangma@users.noreply.github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'xangma <xangma@users.noreply.github.com>'
git_build_date = '2026-09-06 07:50:29 +0000'
git_verbose_msg = """Version: 0.0a9313
Branch: None
Tag: None
Id: 9a6d2adc9aca6349ce004152ed7e49f356214b0f
Builder: xangma <xangma@users.noreply.github.com>
Build date: 2026-09-06 07:50:29 +0000
Repository status is CLEAN: All modifications committed"""

from pycbc._version import *
