# coding: utf-8
# Generated by setup.py for PyCBC on 2026-09-06 11:45:04 +0000.

# general info
version = '0.0a9315'
date = '2026-09-06 11:13:09 +0000'
release = False
last_release = 'None'

# git info
git_hash = 'd544420232428225c214a4be84fbe1262a6d307b'
git_branch = 'None'
git_tag = 'None'
git_author = 'xangma <xangma@users.noreply.github.com>'
git_committer = 'xangma <xangma@users.noreply.github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'xangma <xangma@users.noreply.github.com>'
git_build_date = '2026-09-06 11:45:04 +0000'
git_verbose_msg = """Version: 0.0a9315
Branch: None
Tag: None
Id: d544420232428225c214a4be84fbe1262a6d307b
Builder: xangma <xangma@users.noreply.github.com>
Build date: 2026-09-06 11:45:04 +0000
Repository status is CLEAN: All modifications committed"""

from pycbc._version import *
