# coding: utf-8
# Generated by setup.py for PyCBC on 2026-09-06 11:44:30 +0000.

# general info
version = '0.0a9316'
date = '2026-09-06 11:13:08 +0000'
release = False
last_release = 'None'

# git info
git_hash = 'd840198592a0ca128f4f89d90987a7469ec37c8f'
git_branch = 'None'
git_tag = 'None'
git_author = 'xangma <xangma@users.noreply.github.com>'
git_committer = 'xangma <xangma@users.noreply.github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'xangma <xangma@users.noreply.github.com>'
git_build_date = '2026-09-06 11:44:30 +0000'
git_verbose_msg = """Version: 0.0a9316
Branch: None
Tag: None
Id: d840198592a0ca128f4f89d90987a7469ec37c8f
Builder: xangma <xangma@users.noreply.github.com>
Build date: 2026-09-06 11:44:30 +0000
Repository status is CLEAN: All modifications committed"""

from pycbc._version import *
