# coding: utf-8
# Generated by setup.py for PyCBC on 2026-09-06 11:43:55 +0000.

# general info
version = '0.0a9314'
date = '2026-09-06 11:13:08 +0000'
release = False
last_release = 'None'

# git info
git_hash = '4885b64560e9f39b740e85b6a976898869dd360e'
git_branch = 'None'
git_tag = 'None'
git_author = 'AI Gareth <AI.Gareth@users.noreply.github.com>'
git_committer = 'xangma <xangma@users.noreply.github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'xangma <xangma@users.noreply.github.com>'
git_build_date = '2026-09-06 11:43:55 +0000'
git_verbose_msg = """Version: 0.0a9314
Branch: None
Tag: None
Id: 4885b64560e9f39b740e85b6a976898869dd360e
Builder: xangma <xangma@users.noreply.github.com>
Build date: 2026-09-06 11:43:55 +0000
Repository status is CLEAN: All modifications committed"""

from pycbc._version import *
